[build-system]
requires = [
    "setuptools >= 67.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "classic-signals"
version = "1.0.0"
authors = [
    {name = "Sergey Variasov", email = "variasov@gmail.com"},
]
description = "Simple hub for inverting dependencies"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "readerwriterlock~=1.0.9",
]

[project.urls]
Homepage = "https://github.com/variasov/classic-signals"

[dependency-groups]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["sources"]
namespaces = true
